config/routes.rb
Toqto::Application.routes.draw do
  resources :messages, :users
  
  match "/"      => "home#index", :as => 'home_index'
  match "/about" => "home#about", :as => 'home_about'
  
  root :to => "home#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :content,  :presence => true
  
  belongs_to :sender, :class_name => "User" # picked up by the sender_id
  #has_and_belongs_to_many :recievers, :class_name => "User" # picked up by the reciever_id	
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,  :presence => true
  
  has_many :messages, :foreign_key => "sender_id"
  #has_and_belongs_to_many :recieved_messages, :class_name => "Message", :foreign_key => "reciever_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @test = "Hoi"
    @messages = Message.all
    #.map(&:attributes).to_json
  end
  
  def about
    @page = "About"
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :html, :xml, :json
  
  def index
    @messages = Message.all
    respond_with @messages
    # respond_to do |format|
    #  format.html
    #   format.json { render :json => @messages.map(&:attributes) }
    # end
  end
  
  def show
    @message = Message.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message.to_xml(:except => [:id, :sender_id, :email], :include => :sender) }
    end
  end
  
  def new
    @message = Message.new
    
     respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @message }
      end
  end
  
  def create
    @message = Message.new(params[:message])
    @user = User.find_by_name("Somebody")
    @message.sender = @user
    
    respond_to do |format|
      if @message.save
        format.html { redirect_to home_index_path(), :notice => 'Flirt added! Good luck!' }
      else
        format.html { render :action => "new" }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html
  
  def index
    @users = User.all
    
    respond_with @users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<h1 id="about"><%= @page %></h1>
<%= link_to "home", home_index_path() %>

app/views/home/index.html.erb
<% content_for :head do %>
<%= javascript_include_tag "geo.js" %>	
<% end %>
<div id="result"></div>
<div id="map"></div>
<div id="selected_message">
	
</div>
<%= link_to "New Flirt", new_message_path() %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toqto</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, "https://maps.google.com/maps/api/js?sensor=true&language=en&region=NL" %>
  <%= csrf_meta_tag %>
  <%= yield(:head) %>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=1;">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-touch-fullscreen" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <link rel="apple-touch-startup-image" href="images/loading.png" />
  <link rel="apple-touch-icon" href="images/icon.png"/>
</head>
<body>
	<div id="container">	
		<div id="user_nav">
			<%= link_to "", home_index_path(), :id => "home" %>
		</div>
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
		<div id="content">
			<%= yield %>
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
			<br />
		</div>	
		<%= render 'shared/footer' %>
	</div>
</body>
</html>

app/views/messages/_form.html.erb
<% form_for(@message) do |f| %>
	<% if @message.errors.any? %>
	<% end %>
	
	<div class="field">
    	<%= f.label "Message" %><br />
    	<%= f.text_area :content, :rows => 5, :class => 'post-area' %>
  	</div>
	<div class="field" style="display:none;">
    	<%= f.label "Lat" %><br />
    	<%= f.hidden_field :lat, :class => 'rec-text' %>
  	</div>
	<div class="field" style="display:none;">
    	<%= f.label "Long" %><br />
    	<%= f.hidden_field :long, :class => 'rec-text' %>
  	</div>
  	<div class="actions">
    	<%= f.submit "Post Flirt" %> or <%= link_to 'cancel', home_index_path() %>
  	</div>
	
<% end %>

app/views/messages/_message.html.erb
<div class="message">
	<%= message.content %> | 
	<%= message.sender.name %>
</div>

app/views/messages/index.html.erb
<%= @testje %>
<div id="messages-list">
<%= render @messages %>
</div>

app/views/messages/new.html.erb
<% content_for :head do %>
<%= javascript_include_tag "message.js" %>	
<% end %>
<%= render 'form' %>

app/views/shared/_footer.html.erb
<div id="footer">
	<a href="http://toqto.me" target="_blank">toqto.me</a> is an experiment by <a href="http://www.twitter.com/tikkieseb" target="_blank">Seb</a>
</div>

app/views/users/_user.html.erb
<div class="user">
	<%= user.name %>
</div>

app/views/users/index.html.erb
<div id="user-list">
<%= render @users %>
</div>